// ── Theme export (theme.sh) ───────────────────────────────────────────────────
//
// Resolves the active client theme id to its full palette (via @palmux/shared —
// the SAME data the client renders) and writes it to
// `<configDir>/theme.sh` as shell exports. The user's shell/tmux/delta configs
// source this file and reference ${PALMUX_C_*} (hex) / ${PALMUX_I_*} (256-index),
// so their prompt / status bar / diff colours follow the palmux theme instead of
// being hardcoded. Regenerated on boot and on every theme change; atomic write so
// a shell sourcing it never sees a half-written file.

import { mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import {
  getProfile,
  hex,
  registerDynamicThemes,
  resolveThemePalette,
  type JsonObject,
} from '@palmux/shared';
import { DEFAULT_THEME_ID } from '@palmux/shared';
import { discoverThemes } from './theme-files';
import { buildClaudeTheme, claudeThemePath } from './claude-theme';
import { readDeltaDiffColors, type DiffColors } from './delta-colors';
import { reloadTmuxConfig } from './tmux-reload';
import { runThemeHook } from './theme-hook';

/**
 * Make sure `themeId` resolves to its REAL profile before anything reads it.
 *
 * `getProfile` answers with the default profile for an id it doesn't know, and
 * user/emulator themes only exist after `registerDynamicThemes`. Get that order
 * wrong and a light theme exports as dark — wrong `base`, and (worse) delta's
 * DARK palette dropped onto a light background. Rather than depend on every
 * caller registering first, detect the miss and discover once.
 */
function ensureResolvable(themeId: string): void {
  if (getProfile(themeId).id === themeId) return;
  registerDynamicThemes(discoverThemes());
}

/** git-delta's palette as `#rrggbb` strings, for theme.json consumers. */
function hexDiff(diff: DiffColors): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [key, value] of Object.entries(diff)) {
    if (typeof value === 'number') out[key] = hex(value);
  }
  return out;
}

/** Polarity of a theme id — picks which of delta's two palettes applies. */
const isLightThemeId = (themeId: string): boolean => resolveThemePalette(themeId).light;

/** POSIX single-quote a value (safe for arbitrary strings). */
function shq(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

/** Read the active theme id from the (opaque) persisted settings. */
export function themeIdFrom(settings: JsonObject | undefined): string {
  const id = settings?.['themeId'];
  return typeof id === 'string' && id ? id : DEFAULT_THEME_ID;
}

/** The `theme.sh` file body for a theme id. */
export function buildThemeSh(themeId: string): string {
  const p = resolveThemePalette(themeId);
  const lines: string[] = [
    '# Generated by palmux — active terminal theme palette. DO NOT EDIT (overwritten).',
    '# Source this file, then use ${PALMUX_C_<NAME>} (hex) or ${PALMUX_I_<NAME>} (256-index).',
    '# Names: FG BG BASE MANTLE SURFACE TEXT SUBTEXT ACCENT ACCENT_ALT,',
    '#        RED PEACH MAROON YELLOW GREEN TEAL SKY BLUE LAVENDER MAUVE PINK GRAY, ANSI0..15.',
    `export PALMUX_THEME=${shq(p.id)}`,
    `export PALMUX_THEME_NAME=${shq(p.name)}`,
    `export PALMUX_THEME_LIGHT=${p.light ? '1' : '0'}`,
  ];
  for (const [name, col] of Object.entries(p.colors)) {
    const key = name.toUpperCase();
    lines.push(`export PALMUX_C_${key}=${shq(col.hex)}`);
    lines.push(`export PALMUX_I_${key}=${col.index}`);
  }
  return lines.join('\n') + '\n';
}

/** The `theme.tmux` file body — `@palmux_*` user options (for #{} in format
 *  strings like status-left/right) plus the style options that can't take a
 *  format (status-style, pane borders), mapped to palette roles. `source-file`
 *  this from .tmux.conf; reload with your usual key (e.g. prefix+r). */
export function buildThemeTmux(themeId: string): string {
  const p = resolveThemePalette(themeId);
  const h = (name: string): string => p.colors[name]?.hex ?? '#000000';
  const lines: string[] = [
    '# Generated by palmux — active terminal theme palette. DO NOT EDIT (overwritten).',
    '# source-file this from ~/.tmux.conf; use #{@palmux_<name>} in status formats.',
    `set -gq @palmux_theme "${p.id}"`,
    `set -gq @palmux_light "${p.light ? '1' : '0'}"`,
  ];
  for (const [name, col] of Object.entries(p.colors)) {
    lines.push(`set -gq @palmux_${name} "${col.hex}"`);
  }
  // Style options do NOT expand #{...}, so bake theme colours in directly.
  lines.push(
    `set -g status-style "bg=${h('mantle')},fg=${h('text')}"`,
    `set -g pane-border-style "fg=${h('surface')}"`,
    `set -g pane-active-border-style "fg=${h('blue')}"`,
    `set -g message-style "bg=${h('surface')},fg=${h('text')}"`,
    // The native window-status list defaults to the terminal's own colours (a
    // black band in the middle of the bar). Match it to the bar bg so it blends.
    `set -g window-status-style "bg=${h('mantle')},fg=${h('subtext')}"`,
    `set -g window-status-current-style "bg=${h('mantle')},fg=${h('text')}"`,
  );
  // tmux2k rebuilds the whole status bar from its @tmux2k-<colour> options
  // (which override the named-theme preset). Feed them the palette so the bar
  // follows the palmux theme; set BEFORE tmux2k inits, re-applied on reload.
  // Muted accents as segment BACKGROUNDS. tmux2k reuses `black`/`white` for the
  // segment INK (fg) and the session/time chip fills. Both must stay readable
  // in either polarity, so map them to theme-relative ink tones rather than the
  // literal `text` (which is light on dark themes → washed-out, unreadable fg,
  // and inverts the dark PDEV session chip). darkInk stays dark & lightInk stays
  // light in BOTH themes: on dark, surface (a distinct dark-grey) vs text; on
  // light, text (navy) vs surface (a distinct light-cream).
  const darkInk = p.light ? h('text') : h('surface');
  const lightInk = p.light ? h('surface') : h('text');
  // Segment accent backgrounds: MUTED (blended toward bg) only on light themes;
  // on dark themes use the theme's colours directly (bright, as configured).
  const m = (name: string): string => (p.light ? h(`${name}_muted`) : h(name));
  const tk: Array<[string, string]> = [
    ['bg-main', h('mantle')],
    ['bg-alt', h('surface')],
    ['black', darkInk],
    ['white', lightInk],
    ['text', h('text')],
    ['gray', h('subtext')],
    ['dark-gray', h('surface')],
    ['blue', m('blue')],
    ['dark-blue', m('blue')],
    ['light-blue', m('sky')],
    ['green', m('green')],
    ['dark-green', m('green')],
    ['light-green', m('teal')],
    ['yellow', m('yellow')],
    ['light-yellow', m('yellow')],
    ['dark-yellow', m('peach')],
    ['orange', m('peach')],
    ['light-orange', m('peach')],
    ['dark-orange', m('maroon')],
    ['red', m('red')],
    ['light-red', m('maroon')],
    ['dark-red', m('maroon')],
    ['purple', m('mauve')],
    ['light-purple', m('lavender')],
    ['dark-purple', m('mauve')],
    ['pink', m('pink')],
    ['light-pink', darkInk],
    ['dark-pink', m('pink')],
    // Pane divider inverts the bg lightness (subtext is dark on light themes,
    // light on dark); active divider = accent. Message bar follows the palette.
    ['pane-border', h('subtext')],
    ['pane-active-border', h('blue')],
    ['message-bg', h('surface')],
    ['message-fg', h('text')],
  ];
  for (const [opt, val] of tk) lines.push(`set -gq @tmux2k-${opt} "${val}"`);
  return lines.join('\n') + '\n';
}

/** Write `<configDir>/theme.sh` + `theme.tmux`, plus the Claude Code theme at
 *  `~/.claude/themes/palmux.json`. All atomic, all non-fatal on failure — the
 *  Claude write is isolated so a missing/read-only `~/.claude` can't cost us the
 *  palmux exports. */
export function writeThemeExport(configDir: string, themeId: string): void {
  ensureResolvable(themeId);
  try {
    mkdirSync(configDir, { recursive: true });
    writeAtomic(join(configDir, 'theme.sh'), buildThemeSh(themeId));
    const tmuxPath = join(configDir, 'theme.tmux');
    const tmux = buildThemeTmux(themeId);
    // A `settings` message fires for ANY setting, and boot re-exports whether or
    // not anything moved. Only a real palette change is worth reloading a live
    // tmux for — comparing the rendered body catches exactly that, with no state
    // to keep across restarts.
    const paletteChanged = readIfExists(tmuxPath) !== tmux;
    writeAtomic(tmuxPath, tmux);
    if (paletteChanged) reloadTmuxConfig(tmuxPath);
  } catch {
    /* config dir not writable — the export is a convenience, never fatal */
  }
  // theme.json: everything derived from the active theme, in one machine-readable
  // place. It is the hook's input contract, and useful on its own for any script
  // that wants the palette without parsing shell exports.
  const delta = readDeltaDiffColors();
  const light = isLightThemeId(themeId);
  try {
    writeAtomic(
      join(configDir, 'theme.json'),
      `${JSON.stringify(
        {
          ...resolveThemePalette(themeId),
          // DiffColors holds 0xRRGGBB numbers; JSON consumers want hex strings
          // (a raw number in a Claude theme is an invalid colour and is dropped).
          diff: hexDiff(light ? delta.light : delta.dark),
          claudeThemePath: claudeThemePath(),
        },
        null,
        2,
      )}\n`,
    );
  } catch {
    /* config dir not writable */
  }

  // A hook REPLACES the built-in Claude export: one writer per file, always.
  if (runThemeHook(configDir)) return;

  try {
    const path = claudeThemePath();
    const body = buildClaudeTheme(themeId, light ? delta.light : delta.dark);
    // Only write when the palette actually moved. Claude Code reads a theme at
    // startup and on `/theme`, so every needless rewrite silently ages whatever
    // session is already running — and this runs on EVERY settings message.
    if (readIfExists(path) === body) return;
    mkdirSync(dirname(path), { recursive: true });
    writeAtomic(path, body);
  } catch {
    /* no ~/.claude — nothing consumes the theme, so nothing to report */
  }
}

function readIfExists(path: string): string | undefined {
  try {
    return readFileSync(path, 'utf8');
  } catch {
    return undefined;
  }
}

function writeAtomic(path: string, body: string): void {
  const tmp = `${path}.${process.pid}.tmp`;
  writeFileSync(tmp, body, { encoding: 'utf8', mode: 0o644 });
  renameSync(tmp, path);
}
