#!/usr/bin/env node
// ── palmux systemd service management ─────────────────────────────────────────
//
// Everything needed to run palmux as an always-on boot service, from inside the
// project — no hand-written unit files, no hardcoded machine paths:
//
//   yarn service:install     build, (re)generate the unit from THIS checkout +
//                            THIS node, enable at boot (linger), start
//   yarn service:update      rebuild the client + the bin/ bundle, restart the
//                            service (the restart is a COLD start — terminals
//                            are rebuilt from their restore snapshots, not
//                            handed off). The bundle is rebuilt here because
//                            the unit runs from source: nothing else in the
//                            update path would ever refresh bin/, so the
//                            self-contained runtime silently rots one deploy
//                            behind the service it is supposed to mirror.
//   yarn service:uninstall   stop, disable, remove the unit
//   yarn service:status      status + last log lines
//
// The unit is regenerated on every install, so moving the repo or switching
// node versions is fixed by re-running `yarn service:install`.

import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const unitDir = join(homedir(), '.config', 'systemd', 'user');
const unitPath = join(unitDir, 'palmux.service');
const nodeBin = process.execPath;
const tsxCli = join(repoRoot, 'node_modules', 'tsx', 'dist', 'cli.mjs');
const serverEntry = join(repoRoot, 'packages', 'server', 'src', 'index.ts');

const run = (cmd, opts = {}) => execSync(cmd, { stdio: 'inherit', cwd: repoRoot, ...opts });
const runQuiet = (cmd) => {
  try {
    run(cmd);
    return true;
  } catch {
    return false;
  }
};

const unitFile = `[Unit]
Description=palmux — self-hosted web terminal
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
# Generated by \`yarn service:install\` — re-run it after moving the repo or
# changing node versions. All runtime settings live in ~/.config/palmux/config.json.
ExecStart=${nodeBin} ${tsxCli} ${serverEntry}
WorkingDirectory=${join(repoRoot, 'packages', 'server')}
Restart=always
RestartSec=2
# KillMode=process, NOT the default control-group. A tmux server started from
# inside a palmux shell DAEMONIZES to ppid 1 but stays in this unit's cgroup, so
# the default killed it on every \`systemctl restart\` — taking every tmux session
# on the machine with it. What the user then saw was tmux-resurrect rebuilding
# all of them at once from its last SAVE (not the live state) while palmux's own
# restore typed \`tmux attach\` into three terminals against a server that was
# still being reassembled.
#
# Nothing leaks by leaving the cgroup alone: palmux's shells hold pty masters
# that this process owns, so they get SIGHUP and die when it exits, crash
# included. The tmux server holds none of our fds, which is exactly why it must
# be allowed to outlive us — it is the thing the sessions live in.
KillMode=process

[Install]
WantedBy=default.target
`;

const cmd = process.argv[2];
switch (cmd) {
  case 'install': {
    run('yarn build');
    mkdirSync(unitDir, { recursive: true });
    writeFileSync(unitPath, unitFile);
    run('systemctl --user daemon-reload');
    run('systemctl --user enable --now palmux.service');
    runQuiet('loginctl enable-linger'); // start at boot without a login session
    console.log(`\ninstalled: ${unitPath}`);
    run('systemctl --user status palmux.service --no-pager -n 5');
    break;
  }
  case 'update': {
    run('yarn build');
    run('yarn bundle');
    // Refresh the unit when it has drifted from the template. `update` used to
    // only restart, so a unit-level fix (KillMode, for one) reached nobody until
    // they happened to re-run `install` — which they have no reason to do.
    const current = existsSync(unitPath) ? readFileSync(unitPath, 'utf8') : '';
    if (current !== unitFile) {
      mkdirSync(unitDir, { recursive: true });
      writeFileSync(unitPath, unitFile);
      run('systemctl --user daemon-reload');
      console.log(`unit refreshed: ${unitPath}`);
    }
    run('systemctl --user restart palmux.service');
    run('systemctl --user status palmux.service --no-pager -n 5');
    break;
  }
  case 'uninstall': {
    runQuiet('systemctl --user disable --now palmux.service');
    rmSync(unitPath, { force: true });
    runQuiet('systemctl --user daemon-reload');
    console.log('palmux service removed');
    break;
  }
  case 'status': {
    runQuiet('systemctl --user status palmux.service --no-pager -n 20');
    break;
  }
  default:
    console.log('usage: node scripts/service.mjs <install|update|uninstall|status>');
    process.exit(cmd ? 1 : 0);
}
